[build]
  command = "npm config set registry https://registry.npmjs.org/ && npm config get registry && npm config delete proxy && npm config delete https-proxy && npm config set always-auth false && npm cache clean --force && npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
