[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
   included_files = ["public/players.json"]

[build.environment]
  NODE_VERSION = "20"